WorldNameWidget: Add toggleable data center label
una-xiv/umbra pull request #295
Opened 2024-11-05 22:14 UTC by Drakime

This PR adds an option to display the name of the data center for the world name widget.

### Preview

![image](https://github.com/user-attachments/assets/58877e64-bada-4887-8ca9-66f3535d1dba)

> This was requested on Discord — [View the thread](https://discord.com/channels/1263935915517149298/1300921898573496340)

2024-11-07 05:49 UTC, Bloodsoul commented on Umbra/i18n/de.json
> +    "Widget.WorldName.Config.HideDataCenter.Description": "Blendet den Namen des Rechenzentrums aus.",
`Datenzentrum ausblenden` and `Blendet den Namen des Datenzentrums aus.` would better reflect official naming.

2024-11-07 17:02 UTC, Drakime commented on Umbra/i18n/de.json
> +    "Widget.WorldName.Config.HideDataCenter.Description": "Blendet den Namen des Rechenzentrums aus.",
Thank you for letting me know. I have amended the translation accordingly.

2024-11-08 21:14 UTC, haroldiedema requested changes

2024-11-08 21:14 UTC, haroldiedema commented on Umbra/src/Toolbar/Widgets/Library/WorldName/WorldNameWidget.Config.cs
> +                "HideDataCenter",
Having a checkbox to "hide" things feels counter intuitive (true means false). From a UX perspective, it's better to turn this around. (Enable to show, false by default)

2024-11-08 21:16 UTC, haroldiedema commented on Umbra/src/Toolbar/Widgets/Library/WorldName/WorldNameWidget.Config.cs
> +                "HideDataCenter",
To elaborate, "Hide on home world" is an exception in which case it hides the entire widget under certain conditions. This one works in addition to that, adding mental complexity if it is also inversed.

2024-11-08 21:54 UTC, Drakime commented on Umbra/src/Toolbar/Widgets/Library/WorldName/WorldNameWidget.Config.cs
> +                "HideDataCenter",
I understand what you're saying. I've modified the code so that the data center shows when the checkbox is checked, and false by default.

Translations were also amended in light of this, and some tiny refactoring to save one line of code... :sweat_smile:

2024-11-09 14:53 UTC, haroldiedema approved these changes
Thanks! 😄

2024-11-09 14:53 UTC, merged